[package]
name = "advent-of-code-2020-day04"
version = "0.1.0"
authors = ["fwcd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4"
